/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTosRouteImport } from './routes/(public)/tos'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedOnboardingRouteRouteImport } from './routes/(authenticated)/onboarding/route'
import { Route as authenticatedSettingsIndexRouteImport } from './routes/(authenticated)/settings/index'
import { Route as publicSignResetPasswordRouteImport } from './routes/(public)/sign/reset-password'
import { Route as authenticatedWorkspaceNewRouteImport } from './routes/(authenticated)/workspace/new'
import { Route as authenticatedSpacesIdRouteImport } from './routes/(authenticated)/spaces/$id'
import { Route as authenticatedSettingsProjectStatusesRouteImport } from './routes/(authenticated)/settings/project-statuses'
import { Route as authenticatedOnboardingWorkspaceRouteImport } from './routes/(authenticated)/onboarding/workspace'
import { Route as authenticatedOnboardingCompleteRouteImport } from './routes/(authenticated)/onboarding/complete'
import { Route as authenticatedSettingsPreferencesIndexRouteImport } from './routes/(authenticated)/settings/preferences/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTosRoute = publicTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOnboardingRouteRoute =
  authenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsIndexRoute =
  authenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const publicSignResetPasswordRoute = publicSignResetPasswordRouteImport.update({
  id: '/sign/reset-password',
  path: '/sign/reset-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedWorkspaceNewRoute =
  authenticatedWorkspaceNewRouteImport.update({
    id: '/workspace/new',
    path: '/workspace/new',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSpacesIdRoute = authenticatedSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedSettingsProjectStatusesRoute =
  authenticatedSettingsProjectStatusesRouteImport.update({
    id: '/project-statuses',
    path: '/project-statuses',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedOnboardingWorkspaceRoute =
  authenticatedOnboardingWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => authenticatedOnboardingRouteRoute,
  } as any)
const authenticatedOnboardingCompleteRoute =
  authenticatedOnboardingCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => authenticatedOnboardingRouteRoute,
  } as any)
const authenticatedSettingsPreferencesIndexRoute =
  authenticatedSettingsPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof authenticatedOnboardingRouteRouteWithChildren
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/home': typeof authenticatedHomeRoute
  '/privacy': typeof publicPrivacyRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/tos': typeof publicTosRoute
  '/': typeof publicIndexRoute
  '/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/onboarding/workspace': typeof authenticatedOnboardingWorkspaceRoute
  '/settings/project-statuses': typeof authenticatedSettingsProjectStatusesRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/workspace/new': typeof authenticatedWorkspaceNewRoute
  '/sign/reset-password': typeof publicSignResetPasswordRoute
  '/settings/': typeof authenticatedSettingsIndexRoute
  '/settings/preferences': typeof authenticatedSettingsPreferencesIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof authenticatedOnboardingRouteRouteWithChildren
  '/home': typeof authenticatedHomeRoute
  '/privacy': typeof publicPrivacyRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/tos': typeof publicTosRoute
  '/': typeof publicIndexRoute
  '/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/onboarding/workspace': typeof authenticatedOnboardingWorkspaceRoute
  '/settings/project-statuses': typeof authenticatedSettingsProjectStatusesRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/workspace/new': typeof authenticatedWorkspaceNewRoute
  '/sign/reset-password': typeof publicSignResetPasswordRoute
  '/settings': typeof authenticatedSettingsIndexRoute
  '/settings/preferences': typeof authenticatedSettingsPreferencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/onboarding': typeof authenticatedOnboardingRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(public)/tos': typeof publicTosRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/(authenticated)/onboarding/workspace': typeof authenticatedOnboardingWorkspaceRoute
  '/(authenticated)/settings/project-statuses': typeof authenticatedSettingsProjectStatusesRoute
  '/(authenticated)/spaces/$id': typeof authenticatedSpacesIdRoute
  '/(authenticated)/workspace/new': typeof authenticatedWorkspaceNewRoute
  '/(public)/sign/reset-password': typeof publicSignResetPasswordRoute
  '/(authenticated)/settings/': typeof authenticatedSettingsIndexRoute
  '/(authenticated)/settings/preferences/': typeof authenticatedSettingsPreferencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/settings'
    | '/home'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/tos'
    | '/'
    | '/onboarding/complete'
    | '/onboarding/workspace'
    | '/settings/project-statuses'
    | '/spaces/$id'
    | '/workspace/new'
    | '/sign/reset-password'
    | '/settings/'
    | '/settings/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/home'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/tos'
    | '/'
    | '/onboarding/complete'
    | '/onboarding/workspace'
    | '/settings/project-statuses'
    | '/spaces/$id'
    | '/workspace/new'
    | '/sign/reset-password'
    | '/settings'
    | '/settings/preferences'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/onboarding'
    | '/(authenticated)/settings'
    | '/(authenticated)/home'
    | '/(public)/privacy'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(public)/tos'
    | '/(public)/'
    | '/(authenticated)/onboarding/complete'
    | '/(authenticated)/onboarding/workspace'
    | '/(authenticated)/settings/project-statuses'
    | '/(authenticated)/spaces/$id'
    | '/(authenticated)/workspace/new'
    | '/(public)/sign/reset-password'
    | '/(authenticated)/settings/'
    | '/(authenticated)/settings/preferences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/tos': {
      id: '/(public)/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof publicTosRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/onboarding': {
      id: '/(authenticated)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authenticatedOnboardingRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/': {
      id: '/(authenticated)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof authenticatedSettingsIndexRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(public)/sign/reset-password': {
      id: '/(public)/sign/reset-password'
      path: '/sign/reset-password'
      fullPath: '/sign/reset-password'
      preLoaderRoute: typeof publicSignResetPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/workspace/new': {
      id: '/(authenticated)/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof authenticatedWorkspaceNewRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/spaces/$id': {
      id: '/(authenticated)/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof authenticatedSpacesIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/project-statuses': {
      id: '/(authenticated)/settings/project-statuses'
      path: '/project-statuses'
      fullPath: '/settings/project-statuses'
      preLoaderRoute: typeof authenticatedSettingsProjectStatusesRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/onboarding/workspace': {
      id: '/(authenticated)/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof authenticatedOnboardingWorkspaceRouteImport
      parentRoute: typeof authenticatedOnboardingRouteRoute
    }
    '/(authenticated)/onboarding/complete': {
      id: '/(authenticated)/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof authenticatedOnboardingCompleteRouteImport
      parentRoute: typeof authenticatedOnboardingRouteRoute
    }
    '/(authenticated)/settings/preferences/': {
      id: '/(authenticated)/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof authenticatedSettingsPreferencesIndexRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
  }
}

interface authenticatedOnboardingRouteRouteChildren {
  authenticatedOnboardingCompleteRoute: typeof authenticatedOnboardingCompleteRoute
  authenticatedOnboardingWorkspaceRoute: typeof authenticatedOnboardingWorkspaceRoute
}

const authenticatedOnboardingRouteRouteChildren: authenticatedOnboardingRouteRouteChildren =
  {
    authenticatedOnboardingCompleteRoute: authenticatedOnboardingCompleteRoute,
    authenticatedOnboardingWorkspaceRoute:
      authenticatedOnboardingWorkspaceRoute,
  }

const authenticatedOnboardingRouteRouteWithChildren =
  authenticatedOnboardingRouteRoute._addFileChildren(
    authenticatedOnboardingRouteRouteChildren,
  )

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsProjectStatusesRoute: typeof authenticatedSettingsProjectStatusesRoute
  authenticatedSettingsIndexRoute: typeof authenticatedSettingsIndexRoute
  authenticatedSettingsPreferencesIndexRoute: typeof authenticatedSettingsPreferencesIndexRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsProjectStatusesRoute:
      authenticatedSettingsProjectStatusesRoute,
    authenticatedSettingsIndexRoute: authenticatedSettingsIndexRoute,
    authenticatedSettingsPreferencesIndexRoute:
      authenticatedSettingsPreferencesIndexRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedOnboardingRouteRoute: typeof authenticatedOnboardingRouteRouteWithChildren
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedHomeRoute: typeof authenticatedHomeRoute
  authenticatedSpacesIdRoute: typeof authenticatedSpacesIdRoute
  authenticatedWorkspaceNewRoute: typeof authenticatedWorkspaceNewRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedOnboardingRouteRoute:
    authenticatedOnboardingRouteRouteWithChildren,
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedHomeRoute: authenticatedHomeRoute,
  authenticatedSpacesIdRoute: authenticatedSpacesIdRoute,
  authenticatedWorkspaceNewRoute: authenticatedWorkspaceNewRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
  publicTosRoute: typeof publicTosRoute
  publicIndexRoute: typeof publicIndexRoute
  publicSignResetPasswordRoute: typeof publicSignResetPasswordRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPrivacyRoute: publicPrivacyRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
  publicTosRoute: publicTosRoute,
  publicIndexRoute: publicIndexRoute,
  publicSignResetPasswordRoute: publicSignResetPasswordRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
