/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTosRouteImport } from './routes/(public)/tos'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as authenticatedOnboardingRouteImport } from './routes/(authenticated)/onboarding'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as publicSignResetPasswordRouteImport } from './routes/(public)/sign/reset-password'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTosRoute = publicTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedOnboardingRoute = authenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicSignResetPasswordRoute = publicSignResetPasswordRouteImport.update({
  id: '/sign/reset-password',
  path: '/sign/reset-password',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof authenticatedHomeRoute
  '/onboarding': typeof authenticatedOnboardingRoute
  '/privacy': typeof publicPrivacyRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/tos': typeof publicTosRoute
  '/': typeof publicIndexRoute
  '/sign/reset-password': typeof publicSignResetPasswordRoute
}
export interface FileRoutesByTo {
  '/home': typeof authenticatedHomeRoute
  '/onboarding': typeof authenticatedOnboardingRoute
  '/privacy': typeof publicPrivacyRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/tos': typeof publicTosRoute
  '/': typeof publicIndexRoute
  '/sign/reset-password': typeof publicSignResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(authenticated)/onboarding': typeof authenticatedOnboardingRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(public)/tos': typeof publicTosRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/sign/reset-password': typeof publicSignResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/tos'
    | '/'
    | '/sign/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/tos'
    | '/'
    | '/sign/reset-password'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/home'
    | '/(authenticated)/onboarding'
    | '/(public)/privacy'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(public)/tos'
    | '/(public)/'
    | '/(public)/sign/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/tos': {
      id: '/(public)/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof publicTosRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/onboarding': {
      id: '/(authenticated)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authenticatedOnboardingRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/sign/reset-password': {
      id: '/(public)/sign/reset-password'
      path: '/sign/reset-password'
      fullPath: '/sign/reset-password'
      preLoaderRoute: typeof publicSignResetPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedHomeRoute: typeof authenticatedHomeRoute
  authenticatedOnboardingRoute: typeof authenticatedOnboardingRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedHomeRoute: authenticatedHomeRoute,
  authenticatedOnboardingRoute: authenticatedOnboardingRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
  publicTosRoute: typeof publicTosRoute
  publicIndexRoute: typeof publicIndexRoute
  publicSignResetPasswordRoute: typeof publicSignResetPasswordRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPrivacyRoute: publicPrivacyRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
  publicTosRoute: publicTosRoute,
  publicIndexRoute: publicIndexRoute,
  publicSignResetPasswordRoute: publicSignResetPasswordRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
